Homework9
J0ker001/HW9 pull request #1
Opened 2022-01-25 17:32 UTC by J0ker001

Home 9 is finish

2022-01-25 18:50 UTC, rmuhamedgaliev requested changes
Требуются исправления

2022-01-25 18:50 UTC, rmuhamedgaliev commented on src/ru/skypro/Main.java
> +        Author author = new Author(name, famaly);
Лучше сразу в конструктор передать значения без перменных

2022-01-25 18:50 UTC, rmuhamedgaliev commented on src/ru/skypro/lesson9/Book.java
> +    private final String author;
Тут тип должен быть Author

1. Необходимо создать класс Book, который содержит в себе данные об имени, авторе и годе публикации. Типы полей должны быть String, Author (который мы создадим  в п. 2) и int.
2. Необходимо создать класс Author, который содержит в себе данные об имени и фамилии автора.

2022-01-25 21:28 UTC, rmuhamedgaliev approved these changes
Принято, но обрати внимание на уточнение.

2022-01-25 21:28 UTC, rmuhamedgaliev commented on src/ru/skypro/Main.java
> +        Book book = new Book(nameBook, new Author(name, famaly), yearPublishing);
Тут тоже можно было вместо namebook сразу передать значение, так как эта переменная нигде больше не используется

2022-01-27 19:55 UTC, Avenirre commented on src/ru/skypro/lesson9/Author.java
> +        return Objects.hash(name);
Хэш-функция считается по все полям метода

2022-01-27 19:55 UTC, Avenirre commented on src/ru/skypro/lesson9/Book.java
> +    public boolean equals(Object other) {
См. предыдущий комментарий

2022-01-28 17:58 UTC, Avenirre approved these changes

2022-11-22 17:02 UTC, merged